// GENERATED by tool/generate_grid_assets.dart — do not edit.
// Source of truth: the `grid:` block in packages/leonard_grid_assets/pubspec.yaml.
// Regenerate: dart run tool/generate_grid_assets.dart

/// The asset surface `leonard_grid_assets` vends, as the neutral
/// `grid_sdk` declaration contract.
library;

import 'package:grid_sdk/grid_sdk.dart';

/// The `leonard_grid_assets` asset pack.
abstract final class GridAssetsPack {
  /// The vending Dart package.
  static const String package = 'leonard_grid_assets';

  /// `leonard_grid_assets/skill/test-with-leonard`.
  static const GridAssetDefinition skillTestWithLeonard = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.skill,
      id: 'test-with-leonard',
    ),
    description:
        'Route Dart and Flutter test authoring to the cheapest proving level and load only the selected Leonard reference.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/SKILL.md',
      ),
    ],
  );

  /// `leonard_grid_assets/resource/plain-dart-flutter`.
  static const GridAssetDefinition
  resourcePlainDartFlutter = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.resource,
      id: 'plain-dart-flutter',
    ),
    description:
        'Level 0 reference for tests that prove behavior without Leonard live driving.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/plain-dart-flutter.md',
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/plain-dart-flutter.md',
      ),
    ],
  );

  /// `leonard_grid_assets/resource/widget`.
  static const GridAssetDefinition resourceWidget = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.resource,
      id: 'widget',
    ),
    description:
        'Level 1 reference for testing Leonard extensions and observations without a device.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/widget.md',
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/widget.md',
      ),
    ],
  );

  /// `leonard_grid_assets/resource/scripted-device`.
  static const GridAssetDefinition resourceScriptedDevice = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.resource,
      id: 'scripted-device',
    ),
    description:
        'Level 2 reference for scripted tests against a simulator or emulator.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/scripted-device.md',
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/scripted-device.md',
      ),
    ],
  );

  /// `leonard_grid_assets/resource/hardware`.
  static const GridAssetDefinition resourceHardware = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.resource,
      id: 'hardware',
    ),
    description:
        'Level 3 reference for tests whose behavior exists only on physical hardware.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/hardware.md',
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/hardware.md',
      ),
    ],
  );

  /// `leonard_grid_assets/resource/oracle`.
  static const GridAssetDefinition resourceOracle = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.resource,
      id: 'oracle',
    ),
    description:
        'Level 4 reference for scenarios graded by an independent oracle.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/oracle.md',
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/oracle.md',
      ),
    ],
  );

  /// `leonard_grid_assets/resource/mutation`.
  static const GridAssetDefinition resourceMutation = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.resource,
      id: 'mutation',
    ),
    description:
        'Reference for improving assertion quality through mutation testing.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/mutation.md',
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/mutation.md',
      ),
    ],
  );

  /// `leonard_grid_assets/resource/triage`.
  static const GridAssetDefinition resourceTriage = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.resource,
      id: 'triage',
    ),
    description: 'Reference for diagnosing a failed Leonard test run.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/triage.md',
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path:
            'extension/station_overlay/claude/skills/test-with-leonard/references/triage.md',
      ),
    ],
  );

  /// Every declared asset, in declaration order.
  static const List<GridAssetDefinition> assets = <GridAssetDefinition>[
    skillTestWithLeonard,
    resourcePlainDartFlutter,
    resourceWidget,
    resourceScriptedDevice,
    resourceHardware,
    resourceOracle,
    resourceMutation,
    resourceTriage,
  ];

  /// The validated pack. Built, not `const`: the collections
  /// validate duplicates at construction
  /// (`the_grid#asset-definitions-are-const-collections-are-validated`).
  static final GridAssetPackDefinition definition = GridAssetPackDefinition(
    package: package,
    assets: assets,
  );

  /// This pack's overlay head → target mappings.
  static const Map<String, String> stationOverlayMappings = <String, String>{
    'claude': '.claude',
  };
}
