/// Regenerates the ASCII snapshot literals locked in test/snapshots.dart.
/// Run once, EYEBALL the printed scene, and only then trust the lock file:
///   dart run tool/print_snapshots.dart
// ignore_for_file: avoid_print — eyeball output is the whole point.
library;

import 'dart:io';

import 'package:spike4_tree_terminal/fixture.dart';
import 'package:spike4_tree_terminal/live_loop.dart';
import 'package:spike4_tree_terminal/renderer.dart';

Future<void> main() async {
  final fx = Spike4Fixture();
  final loop = LiveLoop(root: fx.root, notifier: fx.notifier);
  loop.start();

  final initial = renderFront(loop.grid);
  print('--- initial ---');
  print(initial);

  for (final v in [1, 2, 3, 42, 137]) {
    fx.ticker.add(v);
    await Future<void>.delayed(Duration.zero);
  }
  fx.feed.add('done');
  await Future<void>.delayed(Duration.zero);
  await Future<void>.delayed(Duration.zero);

  final after = renderFront(loop.grid);
  print('--- final ---');
  print(after);

  String dartLiteral(String s) =>
      "'${s.split('\n').join("'\n    '\\n").replaceAll(r'$', r'\$')}'";

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/print_snapshots.dart — locked snapshot')
    ..writeln('// literals for test/spike4_test.dart. Regenerate + eyeball')
    ..writeln('// the printed scene before trusting a new lock.')
    ..writeln()
    ..writeln('const String initialSnapshot = ${dartLiteral(initial)};')
    ..writeln()
    ..writeln('const String finalSnapshot = ${dartLiteral(after)};');
  File('test/snapshots.dart').writeAsStringSync(out.toString());
  print('--- wrote test/snapshots.dart ---');

  loop.dispose();
  await fx.dispose();
}
