name: leonard_flutter_test
description: Test support for applications and extensions built with leonard_flutter.
version: 0.1.0
repository: https://github.com/memento-engineering/lenny
resolution: workspace

environment:
  flutter: ">=3.41.0"
  sdk: ^3.11.0

dependencies:
  flutter_test:
    sdk: flutter
  leonard_flutter: ^0.3.0
  vm_service: ^14.2.0

dev_dependencies:
  leonard_agent: ^0.2.0
  lints: ^5.1.0
