import 'dart:io';

/// Writes the generated `butcher.yaml` that narrows a run to selected sources.
///
/// The positional interface is:
///
///     dart run tool/butcher_excludes.dart PACKAGE_DIR [SOURCE...]
///
/// Sources are package-relative `lib/**/*.dart` paths, the same strings the
/// nightly selector emits. butcher's configuration is exclude-only — there is
/// no include list and no negation — so a per-file selection is expressed as
/// its complement: enumerate the package's library sources, subtract the
/// selection, and write the remainder under the `exclude` key.
///
/// An empty selection writes no file at all, which leaves the whole library in
/// scope. A selection naming every source writes an empty exclude list, which
/// says the same thing explicitly.
///
/// The file is generated for the duration of one run and removed afterwards by
/// the caller, so an existing `butcher.yaml` that this tool did not write is a
/// developer's own configuration and is never overwritten.
void main(List<String> arguments) {
  try {
    stdout.writeln(_generate(arguments));
  } on _CliFailure catch (failure) {
    stderr.writeln('error: ${failure.message}');
    exitCode = failure.code;
  }
}

/// The first line of every generated file; its absence marks a hand-authored
/// configuration that must not be clobbered.
const String generatedMarker =
    '# Generated by tool/butcher_excludes.dart for one mutation run.';

String _generate(List<String> arguments) {
  if (arguments.isEmpty) {
    throw const _CliFailure(
      64,
      'usage: butcher_excludes.dart PACKAGE_DIR [SOURCE...]',
    );
  }

  final Directory packageDirectory = Directory(arguments.first).absolute;
  if (!packageDirectory.existsSync()) {
    throw _CliFailure(66, 'package not found: ${arguments.first}');
  }
  if (!File('${packageDirectory.path}/pubspec.yaml').existsSync()) {
    throw _CliFailure(
      66,
      'pubspec.yaml not found under ${packageDirectory.path}',
    );
  }

  final File configuration = File('${packageDirectory.path}/butcher.yaml');
  if (configuration.existsSync() &&
      !configuration.readAsStringSync().startsWith(generatedMarker)) {
    throw _CliFailure(
      70,
      'refusing to overwrite a hand-authored ${configuration.path}',
    );
  }

  final List<String> selection = arguments.skip(1).toList();
  if (selection.isEmpty) {
    if (configuration.existsSync()) {
      configuration.deleteSync();
    }
    return 'butcher.yaml: not written; the whole library is in scope';
  }

  final List<String> sources = _librarySources(packageDirectory);
  final Set<String> selected = <String>{};
  for (final String source in selection) {
    final String normalized = _normalize(source);
    if (!sources.contains(normalized)) {
      throw _CliFailure(
        66,
        'selected source is not a library source of '
        '${packageDirectory.path}: $source',
      );
    }
    selected.add(normalized);
  }

  final List<String> excluded = sources
      .where((String source) => !selected.contains(source))
      .toList();
  final StringBuffer document = StringBuffer()
    ..writeln(generatedMarker)
    ..writeln(
      '# It is the complement of the selected sources; never commit it.',
    );
  if (excluded.isEmpty) {
    document.writeln('exclude: []');
  } else {
    document.writeln('exclude:');
    for (final String source in excluded) {
      document.writeln("  - '${source.replaceAll("'", "''")}'");
    }
  }
  configuration.writeAsStringSync(document.toString());
  return 'butcher.yaml: ${excluded.length} of ${sources.length} sources '
      'excluded, ${selected.length} in scope';
}

/// Every `lib/**/*.dart` under [packageDirectory], package-relative and sorted.
List<String> _librarySources(Directory packageDirectory) {
  final Directory library = Directory('${packageDirectory.path}/lib');
  if (!library.existsSync()) {
    throw _CliFailure(66, 'lib/ not found under ${packageDirectory.path}');
  }
  final int prefix = packageDirectory.path.length + 1;
  final List<String> sources = <String>[];
  for (final FileSystemEntity entity in library.listSync(
    recursive: true,
    followLinks: false,
  )) {
    if (entity is! File || !entity.path.endsWith('.dart')) {
      continue;
    }
    final String relative = _normalize(entity.path.substring(prefix));
    if (_globMetacharacter.hasMatch(relative)) {
      throw _CliFailure(
        70,
        'library source is not expressible as a glob: $relative',
      );
    }
    sources.add(relative);
  }
  sources.sort();
  return sources;
}

String _normalize(String path) => path.replaceAll(r'\', '/');

final RegExp _globMetacharacter = RegExp(r'[*?\[\]{}\\]');

class _CliFailure implements Exception {
  const _CliFailure(this.code, this.message);

  final int code;
  final String message;
}
