#!/usr/bin/env bash
set -euo pipefail

# usage: run_mutation_pilot.sh [dry|full|pr] [package] [file...]
#
#   dry   count the mutants without running any tests
#   full  sweep the whole package
#   pr    sweep only the files listed after the package name
#
# Mode stays argument one for backward compatibility: `run_mutation_pilot.sh
# full` still sweeps leonard_native.
#
# GATING IS OFF. mutation_test exits non-zero whenever the score sits below
# its own quality threshold (80% by default), so a package parked at a known
# score would fail its lane on every run. These lanes report and upload
# instead: the exit code is captured, named in the log, and swallowed. The
# report still records the honest rating -- nothing here rewrites the score,
# it only decouples it from the job outcome. Set MUTATION_GATE=1 to restore
# hard failure once the scores are somewhere worth defending.

workspace_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mode="${1:-full}"
[[ $# -gt 0 ]] && shift
package="${1:-leonard_native}"
[[ $# -gt 0 ]] && shift
files=()
[[ $# -gt 0 ]] && files=("$@")

case "$mode" in
  dry | full | pr) ;;
  *)
    echo "usage: $0 [dry|full|pr] [package] [file...]" >&2
    exit 64
    ;;
esac

package_dir="$workspace_root/packages/$package"
if [[ ! -d "$package_dir" ]]; then
  echo "no such package: $package (looked in $package_dir)" >&2
  exit 66
fi

if [[ "$mode" == "pr" && ${#files[@]} -eq 0 ]]; then
  echo "pr mode needs at least one file, relative to packages/$package" >&2
  exit 64
fi

output_dir="$workspace_root/artifacts/mutation/$package/$mode"
rm -rf "$output_dir"
mkdir -p "$output_dir"

# A Flutter package is driven by `flutter test`, not `dart test`. The sdk-style
# dependency (a bare `flutter:` key) is the signal; it agrees with
# `melos list --flutter` across this workspace. Detected once here and used
# for BOTH the baseline run and the per-mutant runs, so the two cannot drift.
if grep -qE '^[[:space:]]+flutter:[[:space:]]*$' "$package_dir/pubspec.yaml"; then
  test_cmd='flutter test'
else
  test_cmd='dart test'
fi

cd "$package_dir"

rules="$output_dir/mutation_rules.xml"
cat > "$rules" <<XML
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tool/run_mutation_pilot.sh. The builtin rules stay on via
     -b; this document only swaps in the right test runner. -->
<mutations version="1.2">
  <commands>
    <command group="test" expected-return="0" working-directory=".">$test_cmd</command>
  </commands>
</mutations>
XML

mutation_args=(--rules "$rules" -b)

if [[ "$mode" == "dry" ]]; then
  mutation_args+=(--dry --format none)
else
  # A red baseline makes every mutant look "detected". Fail loudly on it --
  # that IS a real failure, and it is gated regardless of MUTATION_GATE.
  $test_cmd

  mutation_args+=(--format all --output "$output_dir")

  coverage_source="$workspace_root/artifacts/coverage/$package.lcov"
  if [[ -f "$coverage_source" ]]; then
    normalized_coverage="$output_dir/$package.lcov"
    sed "s#^SF:packages/$package/#SF:lib/#" \
      "$coverage_source" > "$normalized_coverage"
    mutation_args+=(--coverage "$normalized_coverage")
  else
    echo "note: no lcov at $coverage_source — running without coverage input."
  fi
fi

[[ ${#files[@]} -gt 0 ]] && mutation_args+=("${files[@]}")

set +e
dart run mutation_test "${mutation_args[@]}" 2>&1 | tee "$output_dir/console.txt"
status=${PIPESTATUS[0]}
set -e

if ((status != 0)); then
  echo
  echo "mutation_test exited $status — the score is below its quality threshold."
  if [[ "${MUTATION_GATE:-0}" == "1" ]]; then
    echo "MUTATION_GATE=1 — failing this run."
    exit "$status"
  fi
  echo "Reporting only (gating off). Set MUTATION_GATE=1 to fail on score."
fi
