name: leonard_flutter
description: Host WidgetsBinding for Leonard.
version: 0.1.3
repository: https://github.com/memento-engineering/lenny
resolution: workspace

environment:
  flutter: ">=3.41.0"
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  genesis_perception: ^0.1.2
  leonard_agent: ^0.1.0
  leonard_contract: ^0.1.0
  meta: ^1.16.0
  vm_service: ^14.2.0

dev_dependencies:
  lints: ^5.1.0
